[package]
name = "http-rs"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
authors = ["Kanavaar"]

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
debug = false