name: "CI"
on: ["push", "pull_request"]

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: Run sccache-cache
          uses: mozilla-actions/sccache-action@v0.0.3
        - name: cargo test
          run: cargo test
  cargo-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: cargo-build
        run: cargo build
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1 
